TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rotstirr.db
DATA += rotstirr.proto

#=======================================
include $(TOP)/configure/RULES
